//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public foto()
        {
            this.cliente_foto = new HashSet<cliente_foto>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_proveedor { get; set; }
        public int id_categoria { get; set; }
        public byte[] url_foto { get; set; }
        public Nullable<System.DateTime> fecha_insercion { get; set; }
        public string descripcion { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cliente_foto> cliente_foto { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
